# ========= Persistence =========
persistence:
  redis_url: "rediss://default:ASpEAAIncDI3NDk5ODUzMzg0MWE0MDE5YjQxNjE4ODE3Yjk1NjdlN3AyMTA4MjA@polished-jackass-10820.upstash.io:6379"   # or use REDIS_URL env
  key_prefix: spideybot:v1
  ttl_minutes: 2880

# ========= Trading =========
trading:
  paper: true                 # true=paper, false=live
  base_balance_usdt: 1000     # for paper init
  risk_per_trade_pct: 1.0
  max_concurrent_positions: 10
  min_usdt_order: 10
  live_market_slippage_bps: 10

# ========= Filters =========
filters:
  extra_stables: ["USDY","USDE"]  # optional extra base symbols to treat as stables

# ========= Supply/Demand (optional) =========
supply_demand:
  enabled: false
  timeframe_for_zones: "1h"
  lookback: 300
  impulse_factor: 1.8
  zone_padding_pct: 0.25
  max_age_bars: 300
  mode: "prefer"              # "prefer" or "require"

# ========= Day / Swing / Trend params =========
day_trade_params:
  lookback_high: 30
  vol_sma: 30
  rsi_min: 52
  rsi_max: 78
  atr_mult: 1.5
  stop_mode: "swing"
  day_mtf:
    enabled: true
    confirm_tfs: ["5m","15m","30m","45m"]
    min_confirmations: 2
    require_ema_stack: true
    require_macd_bull: true
    min_rsi: 52

swing_trade_params:
  timeframe: "4h"
  ema20: 20
  ema50: 50
  ema100: 100
  pullback_pct_max: 10.0
  rsi_min: 50
  vol_sma: 20
  breakout_lookback: 34
  stop_mode: "swing"
  atr_mult: 2.0

trend_trade_params:
  ema20: 20
  ema50: 50
  ema100: 100
  pullback_pct_max: 10.0
  rsi_min: 50
  rsi_max: 70
  vol_sma: 20
  breakout_lookback: 55
  stop_mode: "swing"
  atr_mult: 2.0

# ========= Movers (legacy) =========
movers:
  enabled: true
  limit: 500
  min_change_24h: 15.0
  min_volume_usd_24h: 5000000
  max_age_days: 365
  quote: USDT
  cmc_api_key: "${CMC_API_KEY}"     # or set ENV CMC_API_KEY

# ========= ETH gate (Top-100 bullish entries only) =========
eth_gate:
  enabled: true
  timeframe: "1h"
  require_ema_stack: true    # EMA20 > EMA50
  min_rsi: 50
  require_breakout: false
  lookback_breakout: 30

# ========= Bearish detectors + inverse trading =========
bearish_signals:
  enabled: true
  day:
    timeframe: "1h"
    lookback_low: 20
    vol_sma: 20
    require_breakdown: true
    require_vol_confirm: true
    rsi_max: 50
  swing:
    timeframe: "4h"
    lookback_low: 34
    ema_stack_bear: true
    require_vol_confirm: true
    rsi_max: 50
  trend:
    timeframe: "1d"
    lookback_low: 55
    ema20_below_50: true
    rsi_max: 50

bear_mode:
  enabled: true
  inverse_suffixes: ["3S","5S"]   # try BASE3S/USDT, then BASE5S/USDT for trading

# ========= Fallback universe (if CMC→MEXC too small) =========
fallback:
  enabled: true
  min_pairs: 30                 # if fewer than this from mapping, use top-volume fallback
  max_pairs: 60
  min_usd_vol: 2000000

# ========= Discord (webhooks also read from ENV) =========
discord:
  signals_webhook: ""           # fallback if env missing
  trades_webhook: ""            # fallback if env missing

# ========= Futures (stubbed for later) =========
futures:
  enabled: false
