# ========= Persistence =========
persistence:
  redis_url: "rediss://default:ASpEAAIncDI3NDk5ODUzMzg0MWE0MDE5YjQxNjE4ODE3Yjk1NjdlN3AyMTA4MjA@polished-jackass-10820.upstash.io:6379"          # or paste your Upstash URL
  key_prefix: spideybot:v1
  ttl_minutes: 2880

# ========= Trading =========
trading:
  paper: true                 # true=paper, false=live
  base_balance_usdt: 1000     # for paper init
  risk_per_trade_pct: 1.0
  max_concurrent_positions: 10
  min_usdt_order: 10
  live_market_slippage_bps: 10

# ========= Filters =========
filters:
  extra_stables: ["USDY","USDE"]  # add more if needed

# ========= Supply/Demand (optional) =========
supply_demand:
  enabled: false
  timeframe_for_zones: "1h"
  lookback: 300
  impulse_factor: 1.8
  zone_padding_pct: 0.25
  max_age_bars: 300
  mode: "prefer"              # "prefer" or "require"

# ========= Day / Swing / Trend params =========
day_trade_params:
  lookback_high: 30
  vol_sma: 30
  rsi_min: 52
  rsi_max: 78
  atr_mult: 1.5
  stop_mode: "swing"
  day_mtf:
    enabled: true
    confirm_tfs: ["5m","15m","30m","45m"]
    min_confirmations: 2
    require_ema_stack: true
    require_macd_bull: true
    min_rsi: 52

swing_trade_params:
  timeframe: "4h"
  ema20: 20
  ema50: 50
  ema100: 100
  pullback_pct_max: 10.0
  rsi_min: 50
  vol_sma: 20
  breakout_lookback: 34
  stop_mode: "swing"
  atr_mult: 2.0

trend_trade_params:
  ema20: 20
  ema50: 50
  ema100: 100
  pullback_pct_max: 10.0
  rsi_min: 50
  rsi_max: 70
  vol_sma: 20
  breakout_lookback: 55
  stop_mode: "swing"
  atr_mult: 2.0

# ========= Movers (legacy) =========
movers:
  enabled: true
  limit: 500
  min_change_24h: 15.0
  min_volume_usd_24h: 5000000
  max_age_days: 365
  quote: USDT
  cmc_api_key: "${CMC_API_KEY}"

# ========= Discord (webhooks also read from ENV) =========
discord:
  # Prefer environment variables:
  #   DISCORD_SIGNALS_WEBHOOK and DISCORD_TRADES_WEBHOOK
  signals_webhook: ""   # fallback if env missing
  trades_webhook: ""    # fallback if env missing
