exits:
  enabled: true
  tp_plan: "50_25_trail"     # Option 2
  trail_pct: 5               # trailing stop % for the final runner
  use_exit_signals: true     # still log edge exits to signals channel

discord:
  signals:
    enabled: true
    webhook: ${DISCORD_SIGNALS_WEBHOOK}
  trades:
    enabled: true
    webhook: ${DISCORD_TRADES_WEBHOOK}
