# =========================
# MEXC Trader Bot — Config
# =========================

# Use CMC Top-100 (filtered to MEXC/USDT) instead of a manual watchlist
use_top100_dynamic_watchlist: true

# Optional manual list (used only if Top-100 mode is false OR CMC key missing)
symbols_watchlist: []

# Persistence (Redis)
persistence:
  key_prefix: spideybot:v1
  ttl_minutes: 2880
  redis_url: "rediss://default:AW1UAAIncDI4ODk3N2U4MDFhOTA0MmY4YjMxMTkyYmQwODBiYWI2MHAyMjc5ODg@central-possum-27988.upstash.io:6379"     # set in env

# Trading & risk
trading:
  paper: true
  base_balance_usdt: 1000
  risk_per_trade_pct: 1.0
  max_concurrent_positions: 10
  min_usdt_order: 10
  live_market_slippage_bps: 10
  auto_sell_on_exit: true
  auto_sell_on_exit_live: false

# Discord webhooks (split channels) — pulled from ENV
discord:
  enabled: true
  signals_webhook: ${DISCORD_SIGNALS_WEBHOOK}  # env var
  trades_webhook:  ${DISCORD_TRADES_WEBHOOK}   # env var

# Bear-safe: map bearish setups to inverse tokens (e.g., BTC3S/USDT)
bear_mode:
  enabled: true
  inverse_suffixes: ["3S","5S"]

# Day (1h) entries
day_trade_params:
  lookback_high: 30
  vol_sma: 30
  rsi_min: 52
  rsi_max: 78
  btc_filter: true
  btc_symbol: "BTC/USDT"
  btc_ema: 20
  stop_mode: "swing"
  atr_mult: 1.5

# Swing (4h) entries
swing_trade_params:
  timeframe: "4h"
  ema20: 20
  ema50: 50
  ema100: 100
  pullback_pct_max: 10.0
  rsi_min: 50
  vol_sma: 20
  breakout_lookback: 34
  stop_mode: "swing"
  atr_mult: 2.0

# Trend (1d) entries
trend_trade_params:
  ema20: 20
  ema50: 50
  ema100: 100
  pullback_pct_max: 10.0
  rsi_min: 50
  rsi_max: 70
  vol_sma: 20
  breakout_lookback: 55
  stop_mode: "swing"
  atr_mult: 2.0

# Supply/Demand confluence (optional)
supply_demand:
  enabled: false
  mode: "prefer"
  timeframe_for_zones: "1h"
  lookback: 300
  impulse_factor: 1.8
  zone_padding_pct: 0.25
  max_age_bars: 300

# Bearish detectors (feed bear-safe inverse longs)
bearish_signals:
  enabled: true
  day:
    timeframe: "1h"
    lookback_low: 20
    vol_sma: 20
    require_breakdown: true
    require_vol_confirm: true
    rsi_max: 50
  swing:
    timeframe: "4h"
    ema_stack_bear: true
    lookback_low: 34
    require_vol_confirm: true
    rsi_max: 50
  trend:
    timeframe: "1d"
    ema20_below_50: true
    lookback_low: 55
    rsi_max: 50

# Exit logic
exits:
  enabled: true
  day:
    ema_break: 20
    rsi_drop_to: 60
  swing:
    ema_break: 50
    rsi_below: 50
  trend:
    rsi_below: 50

# Performance (paper snapshot each run)
performance:
  enabled: true

# Movers / CMC (used for Top-100 universe)
movers:
  enabled: true
  limit: 100
  min_change_24h: -1000    # unused in Top-100 selection, safe default
  min_volume_usd_24h: 0    # unused in Top-100 selection, safe default
  max_age_days: 5000       # unused in Top-100 selection, safe default
  quote: USDT
  cmc_api_key: ${CMC_API_KEY}   # set in env
